### PR TITLE
Added user-friendly instructions on how to use a GitHub App to obtain the appropriate token

### PR DESCRIPTION
**Pull request by grantnorwood**
Added user-friendly instructions on how to use a GitHub App to obtain the appropriate token, with relevant links to GitHub docs, and an example workflow file.

### CODE REVIEW

**Comment by grantnorwood** [comment]
Thanks, @strumwolf!

**Comment by strumwolf** [comment]
No problem. Thanks for the PR @grantnorwood

**Comment by p0fi** [comment]
I have a question on this topic: Which permissions does the app need to perform this? 

My app has: 
✅ Read access to code, metadata, and packages
✅ Read and write access to deployments and environments

I still can't delete an environment with the error 
```
Resource not accessible by integration
```

**Comment by grantnorwood** [comment]
@p0fi 

> Why deleting an environment would need access to org memberships, projects or teams?

No idea why this is 🤷   It's annoying that we have to manage JWT stuff to delete environments, I wish it was just a secret which could be easily pulled in without messing with private keys.

The way I figured it out, and updated the readme, was not with OAuth.  It's using a GitHub app to generate the private key, using that key to exchange it for a JWT with a limited expiration, and using that JWT as the token when deleting an environment.

The order I followed was what I captured in the readme, and I think I included all of the links to the pages I used for references.

You'll find the private key management after clicking the Edit button for your GitHub App.

image

Generate a new key, and store it in your GitHub Actions secrets so it can be used to generate a JWT, as per the readme _(no OAuth is required)_.

image

**Pull request merged**
